# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AviationConversionTool
                                 A QGIS plugin
 Coordinate format, units of measure conversion
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-10-26
        copyright            : (C) 2020 by Paweł Strzelewicz
        email                : pawel.strzelewicz@wp.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AviationConversionTool class from file AviationConversionTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .aviation_conversion_tool import AviationConversionTool
    return AviationConversionTool(iface)
